spring.application.name=salessavvy

# Railway dynamic port
server.port=${PORT:8080}

# ---- Disable DB (important for first deploy) ----
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# ---- JWT (dummy for now) ----
jwt.secret=test123
jwt.expiration=3600000

# ---- Cashfree (dummy for now) ----
cashfree.client.id=test
cashfree.client.secret=test
cashfree.env=sandbox
